apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
    chart: {{ template "smartcheck.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: external
  selector:
    service: frontend
    release: {{ .Release.Name }}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
    chart: {{ template "smartcheck.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ default 1 .Values.replicas.frontend }}
  template:
    metadata:
      labels:
        service: frontend
        chart: {{ template "smartcheck.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: frontend
          {{- $imageDefaults := .Values.images.defaults }}
          {{- with .Values.images.frontend }}
          {{- if eq (default "" .registry) "-" }}
          image: {{ printf "%s:%s" (required ".repository is required!" .repository) (default $imageDefaults.tag .tag) | quote }}
          {{- else }}
          image: {{ printf "%s/%s:%s" (default $imageDefaults.registry .registry) .repository (default $imageDefaults.tag .tag) | quote }}
          {{- end }}
          imagePullPolicy: {{ default $imageDefaults.pullPolicy .pullPolicy }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: external
          # TODO probes
          # livenessProbe:
          # readinessProbe:
          args: []
          env: []
          resources:
{{ toYaml (default .Values.resources.defaults .Values.resources.frontend) | indent 12 }}
      nodeSelector:
{{ toYaml (default .Values.nodeSelector.defaults .Values.nodeSelector.frontend) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.tolerations.defaults .Values.tolerations.frontend) | indent 8 }}
      restartPolicy: Always

{{ if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend
  labels:
    service: frontend
    chart: {{ template "smartcheck.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      service: frontend
      chart: {{ template "smartcheck.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              service: proxy
              chart: {{ template "smartcheck.chart" . }}
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
      ports:
        - protocol: TCP
          port: 8080
{{- end }}