apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smartcheck.fullname" . }}-db
  labels:
    app: {{ template "smartcheck.name" . }}
    chart: {{ template "smartcheck.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.db.user -}}
  database-user: {{ .Values.db.user | b64enc | quote }}
  {{ else -}}
  database-user: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end -}}
  {{ if .Values.db.password -}}
  database-password: {{ .Values.db.password | b64enc | quote }}
  {{ else -}}
  database-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end -}}
  {{ if .Values.db.secret -}}
  database-secret: {{ .Values.db.secret | b64enc | quote }}
  {{ else -}}
  database-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smartcheck.fullname" . }}-vulnerability-db
  labels:
    app: {{ template "smartcheck.name" . }}
    chart: {{ template "smartcheck.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.vulnerabilityDB.user -}}
  database-user: {{ .Values.db.user | b64enc | quote }}
  {{ else -}}
  database-user: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end -}}
  {{ if .Values.vulnerabilityDB.password -}}
  database-password: {{ .Values.db.password | b64enc | quote }}
  {{ else -}}
  database-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "smartcheck.fullname" . }}-tls-certificate
  labels:
    app: {{ template "smartcheck.name" . }}
    chart: {{ template "smartcheck.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- with .Values.certificate }}
  {{- $cert := genSelfSignedCert (default "example.com" .commonName) (default nil .ipAlternativeNames) (default nil .dnsAlternativeNames) (default 3650 (int .lifetime)) }}
  default_ssl.key: {{ $cert.Key | b64enc | quote }}
  default_ssl.crt: {{ $cert.Cert | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "smartcheck.fullname" . }}-auth
  labels:
    app: {{ template "smartcheck.name" . }}
    chart: {{ template "smartcheck.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  userName: {{ default "administrator" .Values.auth.userName | b64enc | quote }}
  password: {{ default (randAlphaNum 16) .Values.auth.password | b64enc | quote }}
