apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smartcheck.fullname" . }}-activation-code
  labels:
    app: {{ template "smartcheck.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
{{- if not (empty .Values.activationCode) }}
{{- $ac := .Values.activationCode | regexFind "^[A-Z0-9]{2}-[A-Z0-9]{4}-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}$" | required ".Values.activationCode is invalid.  It should be in a form of XX-XXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"  }}
{{- end }}
type: Opaque
data:
  code: {{ default "" .Values.activationCode | toString | b64enc | quote }}
