apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "smartcheck.fullname" . }}-outbound-proxy
  labels:
    service: {{ template "smartcheck.fullname" . }}-outbound-proxy
    chart: {{ template "smartcheck.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  httpProxy: {{ quote (default "" .Values.proxy.httpProxy) }}
  httpsProxy: {{ quote (default "" .Values.proxy.httpsProxy) }}
  noProxy: {{ default "" .Values.proxy.noProxy | join "," | quote }}