{{ if (and .Values.registry.enabled .Values.tasks.registryCleaner.enabled) }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: registry-cleaner
  labels:
    task: registry-cleaner
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
spec:
  startingDeadlineSeconds: 300
  concurrencyPolicy: Replace
  schedule: {{ quote .Values.tasks.registryCleaner.schedule }}
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            task: registry-cleaner
            release: {{ .Release.Name }}
            heritage: {{ .Release.Service }}
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
            {{ $k }}: {{ quote $v }}
{{- end }}
        spec:
          automountServiceAccountToken: true
{{- $securityContextEnabled := .Values.securityContext.enabled }}
{{- $securityContext := default .Values.securityContext.default .Values.securityContext.registryCleaner }}
{{- $podSecurityContext := default .Values.securityContext.default.pod $securityContext.pod }}
{{- $containerSecurityContext := default .Values.securityContext.default.container $securityContext.container }}
{{- if $securityContextEnabled }}
          securityContext:
{{ toYaml $podSecurityContext | indent 12 }}
{{- end }}
          {{- $imageDefaults := .Values.images.defaults }}
          {{- with .Values.images.registryCleaner }}
          {{- $secret := (default (default "" $imageDefaults.imagePullSecret) .imagePullSecret) }}
          {{- if not (eq "" $secret) }}
          imagePullSecrets:
            - name: {{ $secret | quote }}
          {{- end }}
          containers:
            - name: cleaner
{{- if $securityContextEnabled }}
              securityContext:
{{ toYaml $containerSecurityContext | indent 16 }}
{{- end }}
              {{- $project := (default (default "deepsecurity" $imageDefaults.project) .project) }}
              {{- $repository := printf "%s/%s" $project (required ".repository is required!" .repository) }}
              {{- $tag := (default $imageDefaults.tag .tag) }}

              {{- if eq (default "" .registry) "-" }}
              image: {{ printf "%s:%s" $repository $tag | quote }}
              {{- else if eq (default "-" $imageDefaults.registry) "-" }}
              image: {{ printf "%s:%s" $repository $tag | quote }}
              {{- else }}
              image: {{ printf "%s/%s:%s" (default $imageDefaults.registry .registry) $repository $tag | quote }}
              {{- end }}
              imagePullPolicy: {{ default (default "Always" $imageDefaults.pullPolicy) .pullPolicy }}
              {{- end }}
              resources:
{{ toYaml (default .Values.resources.defaults .Values.resources.registryCleaner) | indent 16 }}
              args:
                - purge
                - --registry-url=https://registry:5000
                - --insecure-skip-tls-verify=true
{{- if (and .Values.registry.auth.username .Values.registry.auth.password) }}
                - --username=$(HTPASSWD_SECRET_USERNAME)
                - --password=$(HTPASSWD_SECRET_PASSWORD)
              env:
                - name: HTPASSWD_SECRET_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: registry-auth
                      key: username
                - name: HTPASSWD_SECRET_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: registry-auth
                      key: password
{{- end }}
          restartPolicy: OnFailure
          nodeSelector:
{{ toYaml (default .Values.nodeSelector.defaults .Values.nodeSelector.registryCleaner) | indent 12 }}
          tolerations:
{{ toYaml (default .Values.tolerations.defaults .Values.tolerations.registryCleaner) | indent 12 }}


{{ if (and .Values.networkPolicy.enabled .Values.registry.enabled .Values.tasks.registryCleaner.enabled) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: registry-cleaner
  labels:
    task: registry-cleaner
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
spec:
  podSelector:
    matchLabels:
      task: registry-cleaner
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
      {{ $k }}: {{ quote $v }}
{{- end }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      ports:
  egress:
    - to:
        - podSelector:
            matchLabels:
              service: registry
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
              {{ $k }}: {{ quote $v }}
{{- end }}
      ports:
        - protocol: TCP
          port: 5000

{{- end }}
{{- end -}}
