apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smartcheck.fullname" . }}-db
  labels:
    app: {{ template "smartcheck.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
type: Opaque
data:
  {{ if .Values.db.user -}}
  database-user: {{ .Values.db.user | b64enc | quote }}
  {{ else -}}
  database-user: {{ derivePassword 1 "maximum" (required "You must provide a value for auth.masterPassword. Use --set auth.masterPassword={password} or include a value in your overrides.yaml file. If you are upgrading, use --reuse-values to preserve the original value." .Values.auth.masterPassword) "db-user" .Release.Name | b64enc | quote }}
  {{ end -}}
  {{ if .Values.db.password -}}
  database-password: {{ .Values.db.password | b64enc | quote }}
  {{ else -}}
  database-password: {{ derivePassword 1 "maximum" .Values.auth.masterPassword "db-password" .Release.Name | b64enc | quote }}
  {{ end -}}
  {{ if .Values.db.secret -}}
  database-secret: {{ .Values.db.secret | b64enc | quote }}
  {{ else -}}
  database-secret: {{ derivePassword 1 "maximum" .Values.auth.masterPassword "db-secret" .Release.Name | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smartcheck.fullname" . }}-cursor
  labels:
    app: {{ template "smartcheck.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
type: Opaque
data:
  {{ if .Values.cursor.secret -}}
  secret: {{ .Values.cursor.secret | b64enc | quote }}
  {{ else -}}
  secret: {{ derivePassword 1 "maximum" .Values.auth.masterPassword "cursor-secret" .Release.Name | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smartcheck.fullname" . }}-vulnerability-db
  labels:
    app: {{ template "smartcheck.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
type: Opaque
data:
  {{ if .Values.vulnerabilityDB.user -}}
  database-user: {{ .Values.db.user | b64enc | quote }}
  {{ else -}}
  database-user: {{ derivePassword 1 "maximum" .Values.auth.masterPassword "vulndb-user" .Release.Name | b64enc | quote }}
  {{ end -}}
  {{ if .Values.vulnerabilityDB.password -}}
  database-password: {{ .Values.db.password | b64enc | quote }}
  {{ else -}}
  database-password: {{ derivePassword 1 "maximum" .Values.auth.masterPassword "vulndb-password" .Release.Name | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "smartcheck.fullname" . }}-auth
  labels:
    app: {{ template "smartcheck.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
type: Opaque
data:
  userName: {{ default "administrator" .Values.auth.userName | b64enc | quote }}
  password: {{ default (derivePassword 1 "maximum" .Values.auth.masterPassword (default "administrator" .Values.auth.userName) .Release.Name) .Values.auth.password | b64enc | quote }}

{{ if not .Values.certificate.secret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "smartcheck.fullname" . }}-tls-certificate
  labels:
    app: {{ template "smartcheck.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
type: Opaque
data:
  {{- with .Values.certificate }}
  {{- $cert := genSelfSignedCert (default "example.com" .commonName) (default nil .ipAlternativeNames) (default nil .dnsAlternativeNames) (default 3650 (int .lifetime)) }}
  privateKey: {{ $cert.Key | b64enc | quote }}
  certificate: {{ $cert.Cert | b64enc | quote }}
  {{- end }}
{{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smartcheck.fullname" . }}-outbound-proxy-credentials
  labels:
    app: {{ template "smartcheck.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
type: Opaque
data:
  username: {{ default "" .Values.proxy.username | b64enc | quote }}
  password: {{ default "" .Values.proxy.password | b64enc | quote }}
