{{ if .Values.tasks.scan.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scan
  labels:
    task: scan
    chart: {{ template "smartcheck.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ quote .Values.tasks.scan.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            task: scan
            chart: {{ template "smartcheck.chart" . }}
            release: {{ .Release.Name }}
            heritage: {{ .Release.Service }}
        spec:
          automountServiceAccountToken: false
{{- $securityContextEnabled := .Values.securityContext.enabled }}
{{- $securityContext := default .Values.securityContext.default .Values.securityContext.tasks }}
{{- $podSecurityContext := default .Values.securityContext.default.pod $securityContext.pod }}
{{- $containerSecurityContext := default .Values.securityContext.default.container $securityContext.container }}
{{- if $securityContextEnabled }}
          securityContext:
{{ toYaml $podSecurityContext | indent 12 }}
{{- end }}
          {{- $imageDefaults := .Values.images.defaults }}
          {{- with .Values.images.tasks }}
          {{- $secret := (default $imageDefaults.imagePullSecret .imagePullSecret) | quote }}
          {{- if not (eq "" $secret) }}
          imagePullSecrets:
            - name: {{ $secret }}
          {{- end }}
          containers:
            - name: tasks
{{- if $securityContextEnabled }}
              securityContext:
{{ toYaml $containerSecurityContext | indent 16 }}
{{- end }}
              {{- $project := (default (default "deepsecurity" $imageDefaults.project) .project) }}
              {{- $repository := printf "%s/%s" $project (required ".repository is required!" .repository) }}
              {{- $tag := (default $imageDefaults.tag .tag) }}

              {{- if eq (default "" .registry) "-" }}
              image: {{ printf "%s:%s" $repository $tag | quote }}
              {{- else if eq (default "-" $imageDefaults.registry) "-" }}
              image: {{ printf "%s:%s" $repository $tag | quote }}
              {{- else }}
              image: {{ printf "%s/%s:%s" (default $imageDefaults.registry .registry) $repository $tag | quote }}
              {{- end }}
              imagePullPolicy: {{ default (default "Always" $imageDefaults.pullPolicy) .pullPolicy }}
              {{- end }}
              args:
                - scan
              resources:
{{ toYaml (default .Values.resources.defaults .Values.resources.auth) | indent 16 }}
          restartPolicy: OnFailure
          nodeSelector:
{{ toYaml (default .Values.nodeSelector.defaults .Values.nodeSelector.auth) | indent 12 }}
          tolerations:
{{ toYaml (default .Values.tolerations.defaults .Values.tolerations.auth) | indent 12 }}
{{ end }}
